server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: backend-user
            uri: lb://backend-user
            predicates:
              - Path=/api/user/**
            filters:
              - addAuthenticationHeader
          - id: backend-alim
            uri: lb://backend-alim
            predicates:
              - Path=/api/alim/**
            filters:
              - addAuthenticationHeader
          - id: backend-post
            predicates:
              - Path=/api/post/**
            uri: lb://backend-post
            filters:
              - AddAuthenticationHeader

jwt:
  header: Authorization
  secret-key: AADfaskllewstdjfhjwhreawrkewjr32dsfasdTG764Gdslkj298GsWg86G