server:
  port: 8081

spring:
  cloud:
    config:
      enabled: false
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  datasource:
    url: jdbc:mysql://localhost:13306/user?serverTimezone=UTC&useSSL=true&autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    username: user
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1
      validation-timeout: 5000
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
    open-in-view: false

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

jwt:
  expires-in: 86400 # 1day
  mobile-expires-in: 31536000
  tablet-expires-in: 31536000
  secret-key: AADfaskllewstdjfhjwhreawrkewjr32dsfasdTG764Gdslkj298GsWg86G