server:
  port: 8081

spring:
  cloud:
    discovery:
      client:
        simple:
          instances: # 'my-backend-service'에 대한 인스턴스 정의
            alim-service:
              - service-id: alim-service
                uri: http://localhost:8082
              - service-id: alim-service
                uri: http://localhost:8082