server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:13307/post?serverTimezone=UTC&useSSL=true&autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    username: user
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
    connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
    open-in-view: false

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/